'use strict';
angular.module('app').config(['$stateProvider',
	'$urlRouterProvider',
	'$locationProvider',
	function($stateProvider,$urlRouterProvider,$locationProvider){
		$locationProvider.hashPrefix('');
		$stateProvider.state('main',{
			url:'/main',
			templateUrl:'view/main.html',
			controller:'mainCtrl',
		}).state('position',{
			url:'/position/:id',
			templateUrl:'view/position.html',
			controller:'positionCtrl'
		}).state('company',{
			url:'/positionclass/:id',
			templateUrl:'view/positionClass.html',
			controller:'companyCtrl'
		}).state('search',{
			url:'/search',
			templateUrl:'view/search.html',
			controller:'searchCtrl'
		}).state('login',{
			url:'/login',
			templateUrl:'view/login.html',
			'controller':'loginCtrl'
		}).state('register',{
			url:'/register',
			templateUrl:'view/register.html',
			controller:'registerCtrl'
		}).state('user',{
			url:'/user',
			templateUrl:'view/user.html',
			controller:'userCtrl'
		}).state('store',{
			url:'/store',
			templateUrl:'view/store.html',
			controller:'storeCtrl'
		}).state('post',{
			url:'/post',
			templateUrl:'view/post.html',
			controller:'postCtrl'
		});
		$urlRouterProvider.otherwise('main');
}])
